name: Run L2 Bot

on:
  schedule:
    - cron: '0 7,13,19 * * *' # Runs at 7:00 AM, 1:00 PM, and 7:00 PM UTC
  push:
    branches:
      - main

jobs:
  run-typescript-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run Script
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: npm start
